# Notebook to try export stimulus

In [11]:
# stimulation key to specifically target a stimulation session
key = {'subject_id': 30,
 'setup': 1,
 'session_start_time': 3638885582960,
 'stim_start_time': 3638885599001}

In [18]:
import datajoint as dj
import pandas as pd
import numpy as np
import sys
from pathlib import Path

dj.config['database.host'] = 'at-database3.stanford.edu'
# dj.config['database.user'] = 'pavi'
# dj.config['database.password'] = 'pavi#1'

In [13]:
dj.conn()

DataJoint connection (connected) eywalker@at-database3.stanford.edu:3306

In [14]:
acq = dj.create_virtual_module("acq", "acq")
stim = dj.create_virtual_module("stimulation", "stimulation")
ephys = dj.create_virtual_module("ephys", "ephys")

In [21]:
target_dir = Path("session{subject_id}-{session_start_time}-{stim_start_time}/".format(**key))

In [43]:
stim_constants = (stim.StimTrialGroup & key).fetch1('stim_constants', squeeze=True)

In [72]:
stim_constants_dict = {key: stim_constants[key].item() for key in stim_constants.dtype.fields}

In [78]:
v = (stim.StimConditions & key).fetch('condition_info')

In [83]:
trials = (stim.StimTrials & key).fetch()

In [96]:
info = [{k: e[k] for k in e.dtype.fields} for e in trials]

In [112]:
type(trials)

numpy.ndarray

In [113]:
np.ndarray

numpy.ndarray

In [120]:
def clean_up_structured_array(data):

    # if it is not an array, don't modify
    if not isinstance(data, np.ndarray)
        return data

   
    if data.dtype.names is not None:
        # convert record array into an array of dictionary
        value =[{k: clean_up_structured_array(entry[k]) for k in entry.dtype.names} for entry in data]
        if len(value) == 1:
            value = value[0]
    elif data.dtype.
    return value
    


In [121]:
trial_info = clean_up_structured_array(trials)

In [137]:
trials[0]

np.void((30, 1, 3638885582960, 3638885599001, 1, 81839, 84092, rec.array([[(array([[False]]), array([[ True]]), array([[1437.]]), array([[1200.]]), array([[4000.]]), array([[300.]]), array([[2100.]]), array([[4000.]]), array([[150.]]), array([[-647., -382., -312.,  383.]]), array([[65748.625]]), array([[ 4443.],
                   [13086.],
                   [ 1325.],
                   [ 1620.],
                   [19677.],
                   [19109.],
                   [19432.],
                   [  862.],
                   [  205.],
                   [18681.],
                   [ 1526.],
                   [18864.],
                   [16596.],
                   [10769.],
                   [ 5800.]]), array(['Train'], dtype='<U5'), array([[15.]]), array([[440., 455., 860., 875.]]), rec.array([[(array([[1.55604086e+12]]), array([[65804.303]]), array([[1.55604086e+12]]))]],
                      dtype=[('start', 'O'), ('response', 'O'), ('end', 'O')]), array([[81838.47142496],

In [125]:
trial_info[0]

{'subject_id': np.int64(30),
 'setup': np.int64(1),
 'session_start_time': np.int64(3638885582960),
 'stim_start_time': np.int64(3638885599001),
 'trial_num': np.int64(1),
 'start_time': np.int64(81839),
 'end_time': np.int64(84092),
 'trial_params': {'validTrial': array([array([[False]])], dtype=object),
  'correctResponse': array([array([[ True]])], dtype=object),
  'condition': array([array([[1437.]])], dtype=object),
  'intertrialTime': array([array([[1200.]])], dtype=object),
  'acquireFixationTime': array([array([[4000.]])], dtype=object),
  'holdFixationTime': array([array([[300.]])], dtype=object),
  'delayTime': array([array([[2100.]])], dtype=object),
  'responseTime': array([array([[4000.]])], dtype=object),
  'fixationRadius': array([array([[150.]])], dtype=object),
  'eyeParams': array([array([[-647., -382., -312.,  383.]])], dtype=object),
  'behaviorTimestamp': array([array([[65748.625]])], dtype=object),
  'image_idx_used': array([array([[ 4443.],
                [13086

In [109]:
trials.dtype.names

('subject_id',
 'setup',
 'session_start_time',
 'stim_start_time',
 'trial_num',
 'start_time',
 'end_time',
 'trial_params',
 'valid_trial',
 'stimvalidtrials_ts')

In [100]:
isinstance(trials, np.recarray)

False

In [103]:
type(trials)

numpy.ndarray

In [106]:
trials.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [97]:
info[0]

{'subject_id': np.int64(30),
 'setup': np.int64(1),
 'session_start_time': np.int64(3638885582960),
 'stim_start_time': np.int64(3638885599001),
 'trial_num': np.int64(1),
 'start_time': np.int64(81839),
 'end_time': np.int64(84092),
 'trial_params': rec.array([[(array([[False]]), array([[ True]]), array([[1437.]]), array([[1200.]]), array([[4000.]]), array([[300.]]), array([[2100.]]), array([[4000.]]), array([[150.]]), array([[-647., -382., -312.,  383.]]), array([[65748.625]]), array([[ 4443.],
                    [13086.],
                    [ 1325.],
                    [ 1620.],
                    [19677.],
                    [19109.],
                    [19432.],
                    [  862.],
                    [  205.],
                    [18681.],
                    [ 1526.],
                    [18864.],
                    [16596.],
                    [10769.],
                    [ 5800.]]), array(['Train'], dtype='<U5'), array([[15.]]), array([[440., 455., 860., 875

In [73]:
stim_constants_dict

{'bgColor': array([127.5, 127.5, 127.5]),
 'fixSpotColor': array([255.,   0.,   0.]),
 'fixSpotLocation': array([0., 0.]),
 'fixSpotSize': 10.0,
 'fixAcquireTime': 3000.0,
 'fixHoldTime': 300.0,
 'allowSaccades': 0.0,
 'monitorSize': array([54.6, 30. ]),
 'monitorDistance': 100.0,
 'monitorCenter': array([960., 540.]),
 'monitorType': 'LCD',
 'passive': 1.0,
 'acquireFixation': 1.0,
 'stimulusLocation': array([-310.,  125.]),
 'imgPathPtrn': '/mnt/lab/libraries/Matlab/ExperimentImages/CenterSurround/ExpImages%d.mat',
 'cacheFolder': '/ramdisk/',
 'texFileNumber': 1.0,
 'numTestTrials': 400.0,
 'numTrainTrials': 1600.0,
 'numTestImagesInSeq': 15.0,
 'numTrainImagesInSeq': 15.0,
 'maxTestImages': 75.0,
 'maxTrainImages': 24000.0,
 'testTrialsBlockSize': 200.0,
 'trainTrialsBlockSize': 1600.0,
 'imTime': 120.0,
 'blankTime': 0.0,
 'postStimulusTime': 300.0,
 'color': 0.0,
 'subject': 'Dennis',
 'date': '2019-04-23_12-33-19',
 'sourcefile': '/mnt/lab/libraries/Matlab/ExperimentImages/Cente

In [59]:
stim_constants['fixSpotLocation'].item()

array([0., 0.])

In [62]:
stim_constants['fixSpotLocation']

array(array([0., 0.]), dtype=object)

In [69]:
stim_constants.item()

(array([127.5, 127.5, 127.5]),
 array([255.,   0.,   0.]),
 array([0., 0.]),
 10.0,
 3000.0,
 300.0,
 0.0,
 array([54.6, 30. ]),
 100.0,
 array([960., 540.]),
 'LCD',
 1.0,
 1.0,
 array([-310.,  125.]),
 '/mnt/lab/libraries/Matlab/ExperimentImages/CenterSurround/ExpImages%d.mat',
 '/ramdisk/',
 1.0,
 400.0,
 1600.0,
 15.0,
 15.0,
 75.0,
 24000.0,
 200.0,
 1600.0,
 120.0,
 0.0,
 300.0,
 0.0,
 'Dennis',
 '2019-04-23_12-33-19',
 '/mnt/lab/libraries/Matlab/ExperimentImages/CenterSurround/ExpImages1.mat',
 array([], shape=(0, 0), dtype=float64),
 25000.0,
 'CenterSurroundExperiment',
 array([1920., 1080.]),
 array([0.        , 0.07390974, 0.09766075, 0.12141176, 0.14001124,
        0.15341907, 0.1668269 , 0.18023473, 0.19364256, 0.20471717,
        0.21368787, 0.22265858, 0.23162928, 0.24059999, 0.2495707 ,
        0.2585414 , 0.26731059, 0.27414307, 0.28097556, 0.28780804,
        0.29464052, 0.30147301, 0.30830549, 0.31513797, 0.32197045,
        0.32880294, 0.33514035, 0.34050348, 0.3458

array([255.,   0.,   0.])

In [36]:
import pandas as pd

In [37]:
pd.DataFrame(stim_constants)

ValueError: 2

In [28]:
stim_constants.squeeze()

rec.array((array([[127.5],
       [127.5],
       [127.5]]), array([[255.],
       [  0.],
       [  0.]]), array([[0.],
       [0.]]), array([[10.]]), array([[3000.]]), array([[300.]]), array([[0.]]), array([[54.6],
       [30. ]]), array([[100.]]), array([[960.],
       [540.]]), array(['LCD'], dtype='<U3'), array([[1.]]), array([[1.]]), array([[-310.],
       [ 125.]]), array(['/mnt/lab/libraries/Matlab/ExperimentImages/CenterSurround/ExpImages%d.mat'],
      dtype='<U73'), array(['/ramdisk/'], dtype='<U9'), array([[1.]]), array([[400.]]), array([[1600.]]), array([[15.]]), array([[15.]]), array([[75.]]), array([[24000.]]), array([[200.]]), array([[1600.]]), array([[120.]]), array([[0.]]), array([[300.]]), array([[0.]]), array(['Dennis'], dtype='<U6'), array(['2019-04-23_12-33-19'], dtype='<U19'), array(['/mnt/lab/libraries/Matlab/ExperimentImages/CenterSurround/ExpImages1.mat'],
      dtype='<U72'), array([], shape=(0, 0), dtype=float64), array([[25000.]]), array(['CenterSurroundExp

In [ ]:
k